import 'product.dart';

class ProductsRepository {
  static const _allProducts = <Product>[
    Product(
      category: Category.accessories,
      id: 0,
      featured: true,
      productName: 'Vagabond Sack',
      price: 1200,
    ),
    Product(
      category: Category.accessories,
      id: 1,
      featured: true,
      productName: 'Stella Sunglasses',
      price: 580,
    ),
    Product(
      category: Category.accessories,
      id: 2,
      featured: false,
      productName: 'Whitney Belt',
      price: 350,
    ),
    Product(
      category: Category.accessories,
      id: 3,
      featured: true,
      productName: 'Garden Strand',
      price: 980,
    ),
    Product(
      category: Category.accessories,
      id: 4,
      featured: false,
      productName: 'Strut Earrings',
      price: 340,
    ),
    Product(
      category: Category.accessories,
      id: 5,
      featured: false,
      productName: 'Varsity Socks',
      price: 120,
    ),
    Product(
      category: Category.accessories,
      id: 6,
      featured: false,
      productName: 'Weave Keyring',
      price: 160,
    ),
    Product(
      category: Category.accessories,
      id: 7,
      featured: true,
      productName: 'Gatsby Hat',
      price: 400,
    ),
    Product(
      category: Category.accessories,
      id: 8,
      featured: true,
      productName: 'Shrug Bag',
      price: 1980,
    ),
    Product(
      category: Category.home,
      id: 9,
      featured: true,
      productName: 'Gilt Desk Trio',
      price: 580,
    ),
    Product(
      category: Category.home,
      id: 10,
      featured: false,
      productName: 'Copperwire Rack',
      price: 180,
    ),
    Product(
      category: Category.home,
      id: 11,
      featured: false,
      productName: 'Soothe Ceramic Set',
      price: 280,
    ),
    Product(
      category: Category.home,
      id: 12,
      featured: false,
      productName: 'Hurrahs Tea-set',
      price: 340,
    ),
    Product(
      category: Category.home,
      id: 13,
      featured: true,
      productName: 'Blue-stone Mug',
      price: 180,
    ),
    Product(
      category: Category.home,
      id: 14,
      featured: true,
      productName: 'Rainwater Tray',
      price: 270,
    ),
    Product(
      category: Category.home,
      id: 15,
      featured: true,
      productName: 'Chambray Napkins',
      price: 160,
    ),
    Product(
      category: Category.home,
      id: 16,
      featured: true,
      productName: 'Succulent Planters',
      price: 160,
    ),
    Product(
      category: Category.home,
      id: 17,
      featured: false,
      productName: 'Quartet Table',
      price: 1750,
    ),
    Product(
      category: Category.home,
      id: 18,
      featured: true,
      productName: 'Kitchen Quattro',
      price: 1290,
    ),
    Product(
      category: Category.clothing,
      id: 19,
      featured: false,
      productName: 'Clay Sweater',
      price: 1800,
    ),
    Product(
      category: Category.clothing,
      id: 20,
      featured: false,
      productName: 'Sea Tunic',
      price: 4500,
    ),
    Product(
      category: Category.clothing,
      id: 21,
      featured: false,
      productName: 'Plaster Tunic',
      price: 380,
    ),
    Product(
      category: Category.clothing,
      id: 22,
      featured: false,
      productName: 'White Pinstripe Shirt',
      price: 700,
    ),
    Product(
      category: Category.clothing,
      id: 23,
      featured: false,
      productName: 'Chambray Shirt',
      price: 700,
    ),
    Product(
      category: Category.clothing,
      id: 24,
      featured: true,
      productName: 'Seabreeze Sweater',
      price: 600,
    ),
    Product(
      category: Category.clothing,
      id: 25,
      featured: false,
      productName: 'Gentry Jacket',
      price: 1780,
    ),
    Product(
      category: Category.clothing,
      id: 26,
      featured: false,
      productName: 'Navy Trousers',
      price: 740,
    ),
    Product(
      category: Category.clothing,
      id: 27,
      featured: true,
      productName: 'Walter Henley (White)',
      price: 380,
    ),
    Product(
      category: Category.clothing,
      id: 28,
      featured: true,
      productName: 'Surf and Perf Shirt',
      price: 480,
    ),
    Product(
      category: Category.clothing,
      id: 29,
      featured: true,
      productName: 'Ginger Scarf',
      price: 980,
    ),
    Product(
      category: Category.clothing,
      id: 30,
      featured: true,
      productName: 'Ramona Crossover',
      price: 680,
    ),
    Product(
      category: Category.clothing,
      id: 31,
      featured: false,
      productName: 'Chambray Shirt',
      price: 380,
    ),
    Product(
      category: Category.clothing,
      id: 32,
      featured: false,
      productName: 'Classic White Collar',
      price: 580,
    ),
    Product(
      category: Category.clothing,
      id: 33,
      featured: true,
      productName: 'Cerise Scallop Tee',
      price: 420,
    ),
    Product(
      category: Category.clothing,
      id: 34,
      featured: false,
      productName: 'Shoulder Rolls Tee',
      price: 270,
    ),
    Product(
      category: Category.clothing,
      id: 35,
      featured: false,
      productName: 'Grey Slouch Tank',
      price: 240,
    ),
    Product(
      category: Category.clothing,
      id: 36,
      featured: false,
      productName: 'Sunshirt Dress',
      price: 580,
    ),
    Product(
      category: Category.clothing,
      id: 37,
      featured: true,
      productName: 'Fine Lines Tee',
      price: 580,
    ),
  ];

  static List<Product> loadProducts(Category category) {
    if (category == Category.all) {
      return _allProducts;
    } else {
      return _allProducts.where((p) => p.category == category).toList();
    }
  }
}